=== Inventua/nucleus-core/Nucleus.Web/package.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="Package"
    targetNamespace="urn:nucleus/schemas/package/1.0"
    elementFormDefault="qualified"
    xmlns:package="urn:nucleus/schemas/package/1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="package" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="publisher" type="package:publisher" minOccurs="1" maxOccurs="1" />
				<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="compatibility" type="package:compatibility" minOccurs="0" maxOccurs="1" />
				<xs:element name="components" type="package:components" minOccurs="1" maxOccurs="1" />				
			</xs:sequence>
			<xs:attribute name="id" type="package:guid" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="publisher">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="url" type="xs:string" />
		<xs:attribute name="email" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="compatibility">
		<xs:attribute name="minVersion" type="package:version" use="required" />
		<xs:attribute name="maxVersion" type="package:version" />
	</xs:complexType>
	
	<xs:complexType name="components">
		<xs:sequence>
			<xs:element name="component" type="package:component" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="component">		
		<xs:choice maxOccurs="unbounded">
			<xs:element name="moduleDefinition" type="package:moduleDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="layoutDefinition" type="package:layoutDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="containerDefinition" type="package:containerDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="controlPanelExtensionDefinition" type="package:controlPanelExtensionDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="cleanup" type="package:cleanup" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>

		<xs:attribute name="folderName" type="xs:string" use="required" />
		<xs:attribute name="optional" type="xs:boolean" use="required" />
	</xs:complexType>

	<xs:complexType name="cleanup">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="moduleDefinition" type="package:moduleDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="layoutDefinition" type="package:layoutDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="containerDefinition" type="package:containerDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="moduleDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="classTypeName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="viewAction" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="editAction" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="categories" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="controlPanelExtensionDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="controllerName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="extensionName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="scope" type="package:controlPanelExtensionScope" minOccurs="1" maxOccurs="1" />
			<xs:element name="editAction" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:simpleType name="controlPanelExtensionScope">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Global"/>
			<xs:enumeration value="Site"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="layoutDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="relativePath" type="xs:string" minOccurs="1" maxOccurs="1" />			
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="containerDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="relativePath" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="folder">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required" />		
	</xs:complexType>

	<xs:complexType name="file">
		<xs:attribute name="name" type="xs:string" use="required" />		
	</xs:complexType>

	<xs:simpleType name="guid">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="version">
		<xs:restriction base="xs:string">
			<xs:pattern value="^(?:(\d+)\.)?(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$" />
		</xs:restriction>
	</xs:simpleType>
	
	
</xs:schema>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.AzureSearch/Package.xml
<package id="2818e5f6-9868-4d65-ac7c-4a57179dbc99" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>AzureSearch</name>
  <version>1.0.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com" email="support@inventua,.com" />
  <description>
		Nucleus search providers for Azure Search.
	</description>
  <compatibility minVersion="2.0.0.1" maxVersion="*" />
  <components>
    <component folderName="AzureSearch" optional="false">
      <controlPanelExtensionDefinition id="204D31FE-3B6B-47F8-B435-B8470F6462D5">
        <friendlyName>Azure Search Settings</friendlyName>
        <helpUrl>https://www.nucleus-cms.com/other-extensions/azure-search/</helpUrl>
        <description>Configure Azure Search settings.</description>
        <controllerName>AzureSearchSettings</controllerName>
        <extensionName>AzureSearch</extensionName>
        <scope>Site</scope>
        <editAction>Settings</editAction>
        <icon><![CDATA[&#xf02f;]]></icon>
      </controlPanelExtensionDefinition>
      <file name="readme.txt" />
      <!-- 
        when the project property GenerateEmbeddedFilesManifest=true and your static resources Build Action=Embedded resource, static resource
        files do not need to be included in package.xml (this file) 
      -->
      <!--<file name="viewer.css" />
			<file name="settings.css" />-->
      <folder name="bin">
        <file name="Nucleus.Extensions.AzureSearch.dll" />
        <file name="Azure.Core.dll" />
        <file name="System.ClientModel.dll" />
        <file name="Azure.Search.Documents.dll" />
        <file name="HtmlAgilityPack.dll" />
        <file name="Microsoft.Bcl.AsyncInterfaces.dll" />
        <file name="OpenAI.dll" />
        <file name="Azure.AI.OpenAI.dll" />
      </folder>
      <!-- 
        when the project property RazorCompileOnBuild=true view (.cshtml) files do not need to be included in package.xml (this file) 
      -->
      <!--<folder name="Views">
				<file name="_ViewImports.cshtml" />
				<file name="Viewer.cshtml" />
				<file name="Settings.cshtml" />
			</folder>-->
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.Account/package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="4a09ada0-75a4-4d1e-ab1b-cabbd5d2f481" 
         xmlns="urn:nucleus/schemas/package/1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>User Accounts</name>
  <version>1.0.1</version>
  <publisher name="Inventua" url="http://www.inventua.com" email="support@inventua.com" />
  <description>
		Application install set for the core user account modules (signup and login).			
	</description>
  <compatibility minVersion="1.0.0.0" maxVersion="*" />
  <components>
    <component folderName="Account" optional="false">
      <moduleDefinition id="f0a9ec71-c29e-436e-96e1-72dcdc44c32b">
        <friendlyName>Login</friendlyName>
        <extension>Account</extension>
        <viewController>Login</viewController>
        <viewAction>Index</viewAction>
        <editAction>Edit</editAction>
        <categories>Authentication,Account Management</categories>
      </moduleDefinition>
      <moduleDefinition id="7b25bdaf-14a3-4bad-9c41-972dbbb384a1">
        <friendlyName>User Signup</friendlyName>
        <extension>Account</extension>
        <viewController>Signup</viewController>
        <viewAction>Index</viewAction>
        <editAction>Edit</editAction>
        <categories>Account Management</categories>
      </moduleDefinition>
      <moduleDefinition id="530efacf-b9ff-4bf1-94d9-c357fc8769ed">
        <friendlyName>Change Password</friendlyName>
        <extension>Account</extension>
        <viewController>ChangePassword</viewController>
        <viewAction>Index</viewAction>
        <editAction>Edit</editAction>
        <categories>Account Management</categories>
      </moduleDefinition>
      <moduleDefinition id="1f347233-99e1-47b8-aa78-90ec16c6dbd2">
        <friendlyName>User Profile</friendlyName>
        <extension>Account</extension>
        <viewController>UserProfile</viewController>
        <viewAction>Index</viewAction>
        <editAction>Edit</editAction>
        <categories>Account Management</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="Bin">
        <file name="Nucleus.Modules.Account.dll" />
      </folder>
      <folder name="Views">
        <file name="Signup.cshtml" />
        <file name="SignupSettings.cshtml" />
        <file name="Login.cshtml" />
        <file name="Settings.cshtml" />
        <file name="Recover.cshtml" />
        <file name="ChangePassword.cshtml" />
        <file name="ChangePasswordSettings.cshtml" />
        <file name="UserProfile.cshtml" />
        <file name="UserProfileSettings.cshtml" />
      </folder>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.AzureAIChat/Package.xml
<package id="e9e3de3b-ab7e-49ee-8d91-f65fe28a5f7f" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Azure AI Chat</name>
  <version>3.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus" email="support@inventua.com" />
  <description>
		This module works with the Azure Search extension and service to provide an AI-powered chat service.
	</description>
  <compatibility minVersion="3.0.0.0" maxVersion="3.*" />
  <components>
    <component folderName="AzureAIChat" optional="false">
      <moduleDefinition id="81046b51-6666-414c-b33e-a830daf5855e">
        <friendlyName>Azure AI Chat</friendlyName>
        <extension>AzureAIChat</extension>
        <viewController>AzureAIChatViewerController</viewController>
        <settingsController>AzureAIChatSettingsController</settingsController>
        <viewAction>Index</viewAction>
        <editAction>Settings</editAction>
      </moduleDefinition>
      <file name="readme.txt" />
      <!-- 
        when the project property GenerateEmbeddedFilesManifest=true and your static resources Build Action=Embedded resource, static resource
        files do not need to be included in package.xml (this file) 
      -->
      <!--<file name="viewer.css" />
			<file name="settings.css" />-->
      <folder name="bin">
        <file name="Nucleus.Modules.AzureAIChat.dll" />
        <file name="OpenAI.dll" />
        <file name="System.ClientModel.dll" />
        <file name="Microsoft.Bcl.AsyncInterfaces.dll" />
        <file name="Azure.Core.dll" />
        <file name="Azure.AI.OpenAI.dll" />
      </folder>
      <!-- 
        when the project property RazorCompileOnBuild=true view (.cshtml) files do not need to be included in package.xml (this file) 
      -->
      <!--<folder name="Views">
				<file name="_ViewImports.cshtml" />
				<file name="Viewer.cshtml" />
				<file name="Settings.cshtml" />
			</folder>-->
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.Links/Package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="407c40be-6025-4a7a-bc41-e07e0ae5f917" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Links</name>
  <version>1.2.1</version>
  <publisher name="Inventua" url="http://www.inventua.com" email="support@inventua.com" />
  <description>
		Display a list of links to selected pages, external Urls or files.
	</description>
  <compatibility minVersion="1.2.2.0" maxVersion="*" />
  <components>
    <component folderName="Links" optional="false">
      <moduleDefinition id="374e62b5-024d-4d8d-95a2-e56f476fe887">
        <friendlyName>Links</friendlyName>
        <extension>Links</extension>
        <viewController>Links</viewController>
        <settingsController>Admin</settingsController>
        <viewAction>Index</viewAction>
        <editAction>Settings</editAction>
        <categories>Content</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <file name="viewer.css" />
      <file name="settings.css" />
      <folder name="Bin">
        <file name="Nucleus.Modules.Links.dll" />
      </folder>
      <folder name="Views">
        <file name="Viewer.cshtml" />
        <file name="Settings.cshtml" />
        <file name="_LinksList.cshtml" />
        <file name="_PageMenu.cshtml" />
        <file name="Editor.cshtml" />
        <folder name="ViewerLayouts">
          <file name="Table.cshtml" />
          <file name="Ordered List.cshtml" />
          <file name="Unordered List.cshtml" />
          <file name="Tile.cshtml" />
          <file name="Tile.css" />
        </folder>
      </folder>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Special.Modules/Nucleus.SAML.Server/Package.xml
<package id="22fd6994-e5b6-4215-b64f-1be4f85aa6eb" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>SAML Server</name>
  <version>2.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus/" email="support@inventua.com" />
  <description>
		The SAML server extension implements the SAML2 protocol to provide authentication (single-signon) services 
		to other web sites and applications. Users can use their Nucleus credentials to access web sites which are 
		configured to use Nucleus as their SAML2 identity provider.
	</description>
  <compatibility minVersion="2.0.0.0" maxVersion="2.*" />
  <components>
    <component folderName="SAMLServer" optional="false">
      <controlPanelExtensionDefinition id="01CC95F7-20AD-4776-97A9-40B32F6D0968">
        <friendlyName>SAML Server</friendlyName>
        <description>Configure SAML server.</description>
        <controllerName>SAMLServerAdmin</controllerName>
        <extensionName>SAMLServer</extensionName>
        <scope>Site</scope>
        <editAction>Settings</editAction>
      </controlPanelExtensionDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <file name="settings.css" />
      <file name="_ViewImports.cshtml" />
      <folder name="bin">
        <file name="Nucleus.SAML.Server.dll" />
        <file name="ITfoxtec.Identity.Saml2.dll" />
        <file name="ITfoxtec.Identity.Saml2.MvcCore.dll" />
        <file name="Microsoft.IdentityModel.Abstractions.dll" />
        <file name="Microsoft.IdentityModel.JsonWebTokens.dll" />
        <file name="Microsoft.IdentityModel.Logging.dll" />
        <file name="Microsoft.IdentityModel.Tokens.dll" />
        <file name="Microsoft.IdentityModel.Tokens.Saml.dll" />
        <file name="Microsoft.IdentityModel.Xml.dll" />
        <file name="System.IdentityModel.Tokens.Jwt.dll" />
        <file name="System.ServiceModel.Primitives.dll" />
        <file name="System.ServiceModel.Security.dll" />
      </folder>
      <folder name="Views">
        <file name="Settings.cshtml" />
        <file name="Editor.cshtml" />
        <file name="_ClientAppsList.cshtml" />
        <file name="_PageMenu.cshtml" />
      </folder>
      <cleanup>
        <!-- assemblies from version 1.3.0 which are no longer used  -->
        <folder name="bin">
          <file name="Microsoft.Bcl.AsyncInterfaces.dll" />
          <file name="System.ServiceModel.dll" />
          <file name="System.Private.ServiceModel.dll" />
        </folder>
      </cleanup>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.GoogleAnalytics/Package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="5a74caf7-c328-466c-85aa-db9861c44700" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Google Analytics</name>
  <version>2.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus/" email="support@inventua.com" />
  <description>
    Use this extension to add Google Analytics reporting to your site.
  </description>
  <compatibility minVersion="2.0.0.0" maxVersion="2.*" />
  <components>
    <component folderName="GoogleAnalytics" optional="false">
      <controlPanelExtensionDefinition id="955b089f-f002-446e-bde0-71f3fe64caab">
        <friendlyName>Google Analytics</friendlyName>
        <description>Configure Google Analytics settings.</description>
        <controllerName>GoogleAnalytics</controllerName>
        <extensionName>GoogleAnalytics</extensionName>
        <scope>Site</scope>
        <editAction>Settings</editAction>
        <icon><![CDATA[&#xef3e;]]></icon>
      </controlPanelExtensionDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="bin">
        <file name="Nucleus.Extensions.GoogleAnalytics.dll" />
      </folder>
      <cleanup>
        <file name="settings.css" />
        <file name="viewer.css" />
        <folder name="Views">
          <file name="Settings.cshtml" />
          <file name="AnalyticsScript.cshtml" />
        </folder>
      </cleanup>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.Media/package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="0A536478-E9A3-4DB6-9D1A-0583B0710B5B" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Media</name>
  <version>1.3.0</version>
  <publisher name="Inventua" url="http://www.inventua.com" email="support@inventua.com" />
  <description>
    The media module presents multimedia content on a page.  It can be used to show video, images, PDF documents within your page, and will render a download link for other file types.
  </description>
  <compatibility minVersion="1.3.0.0" maxVersion="*" />
  <components>
    <component folderName="Media" optional="false">
      <moduleDefinition id="2ffdf8a4-edab-48e5-80c6-7b068e4721bb">
        <friendlyName>Media</friendlyName>
        <extension>Media</extension>
        <viewController>Media</viewController>
        <viewAction>Index</viewAction>
        <editAction>Edit</editAction>
        <categories>Content,Media</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <file name="_ViewImports.cshtml" />
      <file name="media.css" />
      <folder name="Bin">
        <file name="Nucleus.Modules.Media.dll" />
      </folder>
      <folder name="Views">
        <file name="Viewer.cshtml" />
        <file name="Settings.cshtml" />
      </folder>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.Maps/Package.xml
<package id="fa397b8f-9ec2-4340-b1a7-638796e9de2f" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Maps</name>
  <version>1.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com" email="support@inventua.com" />
  <description>The maps modules displays a static map, using the Azure or Google Maps service.</description>
  <compatibility minVersion="2.0.0.0" maxVersion="*" />
  <components>
    <component folderName="Maps" optional="false">
      <moduleDefinition id="fc20b321-1803-429b-8326-e6d0b6b693ef">
        <friendlyName>Maps</friendlyName>
        <extension>Maps</extension>
        <viewController>MapsViewerController</viewController>
        <settingsController>MapsSettingsController</settingsController>
        <viewAction>Index</viewAction>
        <editAction>Settings</editAction>
      </moduleDefinition>
      <file name="readme.txt" />
      <!-- 
        when the project property GenerateEmbeddedFilesManifest=true and your static resources Build Action=Embedded resource, static resource
        files do not need to be included in package.xml (this file) 
      -->
      <!--<file name="viewer.css" />
			<file name="settings.css" />-->
      <folder name="bin">
        <file name="Nucleus.Modules.Maps.dll" />
        <file name="Microsoft.Identity.Client.dll" />
        <file name="Azure.Core.dll" />
        <file name="Microsoft.Bcl.AsyncInterfaces.dll" />
        <file name="System.ClientModel.dll" />
        <file name="Azure.Maps.Common.dll" />
        <file name="Microsoft.Identity.Client.Extensions.Msal.dll" />
        <file name="Azure.Maps.Rendering.dll" />
        <file name="Azure.Identity.dll" />
        <file name="Azure.Maps.Search.dll" />
      </folder>
      <!-- 
        when the project property RazorCompileOnBuild=true view (.cshtml) files do not need to be included in package.xml (this file) 
      -->
      <!--<folder name="Views">
				<file name="_ViewImports.cshtml" />
				<file name="Viewer.cshtml" />
				<file name="Settings.cshtml" />
			</folder>-->
    </component>
  </components>
</package>
