=== Inventua/nucleus-core/Nucleus.Web/package.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="Package"
    targetNamespace="urn:nucleus/schemas/package/1.0"
    elementFormDefault="qualified"
    xmlns:package="urn:nucleus/schemas/package/1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="package" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="publisher" type="package:publisher" minOccurs="1" maxOccurs="1" />
				<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="compatibility" type="package:compatibility" minOccurs="0" maxOccurs="1" />
				<xs:element name="components" type="package:components" minOccurs="1" maxOccurs="1" />				
			</xs:sequence>
			<xs:attribute name="id" type="package:guid" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="publisher">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="url" type="xs:string" />
		<xs:attribute name="email" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="compatibility">
		<xs:attribute name="minVersion" type="package:version" use="required" />
		<xs:attribute name="maxVersion" type="package:version" />
	</xs:complexType>
	
	<xs:complexType name="components">
		<xs:sequence>
			<xs:element name="component" type="package:component" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="component">		
		<xs:choice maxOccurs="unbounded">
			<xs:element name="moduleDefinition" type="package:moduleDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="layoutDefinition" type="package:layoutDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="containerDefinition" type="package:containerDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="controlPanelExtensionDefinition" type="package:controlPanelExtensionDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="cleanup" type="package:cleanup" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>

		<xs:attribute name="folderName" type="xs:string" use="required" />
		<xs:attribute name="optional" type="xs:boolean" use="required" />
	</xs:complexType>

	<xs:complexType name="cleanup">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="moduleDefinition" type="package:moduleDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="layoutDefinition" type="package:layoutDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="containerDefinition" type="package:containerDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="moduleDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="classTypeName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="viewAction" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="editAction" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="categories" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="controlPanelExtensionDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="controllerName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="extensionName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="scope" type="package:controlPanelExtensionScope" minOccurs="1" maxOccurs="1" />
			<xs:element name="editAction" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:simpleType name="controlPanelExtensionScope">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Global"/>
			<xs:enumeration value="Site"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="layoutDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="relativePath" type="xs:string" minOccurs="1" maxOccurs="1" />			
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="containerDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="relativePath" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="folder">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required" />		
	</xs:complexType>

	<xs:complexType name="file">
		<xs:attribute name="name" type="xs:string" use="required" />		
	</xs:complexType>

	<xs:simpleType name="guid">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="version">
		<xs:restriction base="xs:string">
			<xs:pattern value="^(?:(\d+)\.)?(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$" />
		</xs:restriction>
	</xs:simpleType>
	
	
</xs:schema>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.Smtp/Package.xml
<package id="2cefdc41-bb7c-48c7-9dd0-9f1975bcd502" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Smtp Mail</name>
  <version>2.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com" email="support@inventua.com" />
  <description>
		Adds support for sending emails using SMTP.
	</description>
  <compatibility minVersion="2.0.0.0" maxVersion="2.*" />
  <components>
    <component folderName="Smtp Mail" optional="false">
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="bin">
        <file name="Nucleus.Extensions.Smtp.dll" />
        <file name="MailKit.dll" />
        <file name="MimeKit.dll" />
        <file name="BouncyCastle.Cryptography.dll" />
        <file name="System.Security.Cryptography.Pkcs.dll" />
      </folder>
      <cleanup>
        <folder name="Views">
          <file name="_SmtpSettings.cshtml" />
          <file name="_PickupDirectorySettings.cshtml" />
        </folder>        
      </cleanup>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.DeveloperTools/Nucleus.DeveloperTools.VisualStudioTemplates/Template Source Code/Simple Extension Project Template/package.xml
<?xml version="1.0" encoding="utf-8" ?>
<package id="$guid1$" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
	<name>$nucleus_extension_name$</name>
	<version>1.0.0</version>
	<publisher name="$publisher_name$" url="$publisher_url$" email="$publisher_email$" />
	<description>
		$nucleus_extension_description$
	</description>
	<compatibility minVersion="1.0.1.0" maxVersion="*" />
	
	<components>
		<component folderName="$nucleus_extension_name$" optional="false">
			<moduleDefinition id="$guid2$">
				<friendlyName>$nucleus_extension_friendlyname$</friendlyName>
				<extension>$nucleus_extension_name$</extension>
				<viewController>$nucleus_extension_name$Controller</viewController>
				<settingsController>$nucleus_extension_name$AdminController</settingsController>
				<viewAction>Index</viewAction>
				<editAction>Settings</editAction>
			</moduleDefinition>

			<file name="readme.txt" />
			<file name="viewer.css" />
			<file name="settings.css" />
			
			<folder name="Bin">
				<file name="$nucleus_extension_namespace$.dll" />
			</folder>
			
			<folder name="Views">
				<file name="_ViewImports.cshtml" />
				<file name="Viewer.cshtml" />
				<file name="Settings.cshtml" />
			</folder>
			
		</component>
	</components>
	
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.AdvancedSiteMap/Package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="87fd4141-aeb9-4d31-8ee6-793970990b0c" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Advanced SiteMap</name>
  <version>1.3.0</version>
  <publisher name="Inventua" url="https://www.nucleus-cms.com" email="support@inventua.com" />
  <description>
		The Advanced SiteMap extension replaces the built-in Nucleus component which generates a `sitemap.xml` file for use by external search
		engines.  It implements the Nucleus search index manager interface so that the generated site map can include additional entries from
		extensions which submit meta-data to the search system, like the Documents, Forums and Publish modules.
	</description>
  <compatibility minVersion="1.3.0" maxVersion="*" />
  <components>
    <component folderName="AdvancedSiteMap" optional="false">
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="Bin">
        <file name="Nucleus.Extensions.AdvancedSiteMap.dll" />
      </folder>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.MultiContent/Package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="86246671-4a20-4803-a74a-48b3b2d1cc26" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Multi-Content</name>
  <version>3.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus/" email="support@inventua.com" />
  <description>
    Present content in various forms: alert, tabbed, carousel, accordion, grid, faq and plain.
  </description>
  <compatibility minVersion="3.0.0.0" maxVersion="3.*" />
  <components>
    <component folderName="MultiContent" optional="false">
      <moduleDefinition id="c690ad88-0438-48cf-b977-97fe53b7118f">
        <friendlyName>Multi-Content</friendlyName>
        <helpUrl>https://www.nucleus-cms.com/documentation/modules/multi-content/</helpUrl>
        <extension>MultiContent</extension>
        <viewController>MultiContent</viewController>
        <viewAction>Index</viewAction>
        <editAction>Settings</editAction>
        <categories>Content</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="bin">
        <file name="Nucleus.Modules.MultiContent.dll" />
      </folder>
      <cleanup>
        <file name="viewer.css" />
        <file name="settings.css" />
        <folder name="Views">
          <file name="Viewer.cshtml" />
          <file name="Settings.cshtml" />
          <file name="_ContentList.cshtml" />
          <file name="Editor.cshtml" />
          <folder name="ViewerLayouts">
            <file name="Accordion.cshtml" />
            <file name="Alert.cshtml" />
            <file name="Carousel.cshtml" />
            <file name="Tabs.cshtml" />
            <file name="Pills.cshtml" />
            <file name="Faq.cshtml" />
          </folder>
          <folder name="LayoutSettings">
            <file name="_AccordionSettings.cshtml" />
            <file name="_AlertSettings.cshtml" />
            <file name="_CarouselSettings.cshtml" />
            <file name="_TabsSettings.cshtml" />
            <file name="_PillsSettings.cshtml" />
            <file name="_FaqSettings.cshtml" />
          </folder>
        </folder>
      </cleanup>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.SendGrid/Package.xml
<package id="09aeadfd-536e-44d4-acdf-cf1cf6d86629" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>SendGrid Mail</name>
  <version>2.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com" email="support@inventua.com" />
  <description>
		Adds support for sending emails using the Twilio SendGrid API.
	</description>
  <compatibility minVersion="2.0.0.0" maxVersion="2.*" />
  <components>
    <component folderName="SendGrid Mail" optional="false">
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="bin">
        <file name="Nucleus.Extensions.SendGrid.dll" />
        <file name="StarkbankEcdsa.dll" />
        <file name="SendGrid.dll" />
      </folder>
      <folder name="Views">
        <file name="_SendGridSettings.cshtml" />
      </folder>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.TypeSense/Package.xml
<package id="1406f868-cfc0-473c-9122-8e7304edd91f" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>TypeSense</name>
  <version>1.0.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus" email="support@inventua.com" />
  <description>
		Search provider for TypeSense.
	</description>
  <compatibility minVersion="2.1.0.0" maxVersion="*" />
  <components>
    <component folderName="TypeSense" optional="false">
      <controlPanelExtensionDefinition id="d14d2458-9f38-4aae-9275-153eb729d679">
        <friendlyName>TypeSense</friendlyName>
        <helpUrl>https://www.nucleus-cms.com/other-extensions/typesense-search/</helpUrl>
        <description>Configure TypeSense Search settings.</description>
        <controllerName>TypeSenseSettingsController</controllerName>
        <extensionName>TypeSense</extensionName>
        <scope>Site</scope>
        <editAction>Settings</editAction>
        <icon><![CDATA[&#xf02f;]]></icon>
      </controlPanelExtensionDefinition>
      <file name="readme.txt" />
      <!-- 
        when the project property GenerateEmbeddedFilesManifest=true and your static resources Build Action=Embedded resource, static resource
        files do not need to be included in package.xml (this file) 
      -->
      <!--<file name="viewer.css" />
			<file name="settings.css" />-->
      <folder name="bin">
        <file name="Nucleus.Extensions.TypeSense.dll" />
        <file name="Typesense.dll" />
      </folder>
      <!-- 
        when the project property RazorCompileOnBuild=true view (.cshtml) files do not need to be included in package.xml (this file) 
      -->
      <!--<folder name="Views">
				<file name="_ViewImports.cshtml" />
				<file name="Viewer.cshtml" />
				<file name="Settings.cshtml" />
			</folder>-->
      <cleanup>
        <folder name="bin">
          <file name="HtmlAgilityPack.dll" />
        </folder>
      </cleanup>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.AzureEmailCommunications/Package.xml
<package id="83aac7bc-fb2d-4d0e-ac9b-63f381711851" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>AzureEmailCommunications</name>
  <version>1.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus/" email="support@inventua.com" />
  <description>
		Adds support for sending emails using a Azure Email Communications service.
	</description>
  <compatibility minVersion="2.0.0.0" maxVersion="*" />
  <components>
    <component folderName="AzureEmailCommunications" optional="false">
      <file name="readme.txt" />
      <!-- 
        when the project property GenerateEmbeddedFilesManifest=true and your static resources Build Action=Embedded resource, static resource
        files do not need to be included in package.xml (this file) 
      -->
      <!--<file name="viewer.css" />
			<file name="settings.css" />-->
      <file name="license.txt" />
      <folder name="bin">
        <file name="Nucleus.Extensions.AzureEmailCommunications.dll" />
        <file name="Azure.Communication.Email.dll" />
      </folder>
      <!-- 
        when the project property RazorCompileOnBuild=true view (.cshtml) files do not need to be included in package.xml (this file) 
      -->
      <!--<folder name="Views">
				<file name="_ViewImports.cshtml" />
				<file name="Viewer.cshtml" />
				<file name="Settings.cshtml" />
			</folder>-->
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.DeveloperTools/Nucleus.DeveloperTools.VisualStudioTemplates/Template Source Code/Empty Extension Project Template/package.xml
<?xml version="1.0" encoding="utf-8" ?>
<package id="$guid1$" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
	<name>$nucleus.extension.name$</name>
	<version>1.0.0</version>
	<publisher name="$publisher.name$" url="$publisher.url$" email="$publisher.email$" />
	<description>
		$nucleus.extension.description$
	</description>
	<compatibility minVersion="1.0.1.0" maxVersion="*" />
	
	<components>
		<component folderName="$nucleus.extension.name$" optional="false">
			<file name="readme.txt" />

			<folder name="bin">
				<file name="$nucleus.extension.namespace$.dll" />
			</folder>			
		</component>
	</components>
	
</package>
