=== Inventua/nucleus-core/Nucleus.Web/package.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="Package"
    targetNamespace="urn:nucleus/schemas/package/1.0"
    elementFormDefault="qualified"
    xmlns:package="urn:nucleus/schemas/package/1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="package" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="publisher" type="package:publisher" minOccurs="1" maxOccurs="1" />
				<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="compatibility" type="package:compatibility" minOccurs="0" maxOccurs="1" />
				<xs:element name="components" type="package:components" minOccurs="1" maxOccurs="1" />				
			</xs:sequence>
			<xs:attribute name="id" type="package:guid" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="publisher">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="url" type="xs:string" />
		<xs:attribute name="email" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="compatibility">
		<xs:attribute name="minVersion" type="package:version" use="required" />
		<xs:attribute name="maxVersion" type="package:version" />
	</xs:complexType>
	
	<xs:complexType name="components">
		<xs:sequence>
			<xs:element name="component" type="package:component" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="component">		
		<xs:choice maxOccurs="unbounded">
			<xs:element name="moduleDefinition" type="package:moduleDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="layoutDefinition" type="package:layoutDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="containerDefinition" type="package:containerDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="controlPanelExtensionDefinition" type="package:controlPanelExtensionDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="cleanup" type="package:cleanup" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>

		<xs:attribute name="folderName" type="xs:string" use="required" />
		<xs:attribute name="optional" type="xs:boolean" use="required" />
	</xs:complexType>

	<xs:complexType name="cleanup">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="moduleDefinition" type="package:moduleDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="layoutDefinition" type="package:layoutDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="containerDefinition" type="package:containerDefinition" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="moduleDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="classTypeName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="viewAction" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="editAction" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="categories" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="controlPanelExtensionDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="controllerName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="extensionName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="scope" type="package:controlPanelExtensionScope" minOccurs="1" maxOccurs="1" />
			<xs:element name="editAction" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:simpleType name="controlPanelExtensionScope">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Global"/>
			<xs:enumeration value="Site"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="layoutDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="relativePath" type="xs:string" minOccurs="1" maxOccurs="1" />			
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="containerDefinition">
		<xs:sequence>
			<xs:element name="friendlyName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="relativePath" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="package:guid" use="required" />
	</xs:complexType>

	<xs:complexType name="folder">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="file" type="package:file" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="folder" type="package:folder" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required" />		
	</xs:complexType>

	<xs:complexType name="file">
		<xs:attribute name="name" type="xs:string" use="required" />		
	</xs:complexType>

	<xs:simpleType name="guid">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="version">
		<xs:restriction base="xs:string">
			<xs:pattern value="^(?:(\d+)\.)?(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$" />
		</xs:restriction>
	</xs:simpleType>
	
	
</xs:schema>

=== Inventua/nucleus-core/Nucleus.Special.Modules/Nucleus.XmlDocumentation/Package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="9384abed-a555-46a2-aa89-648d37216225" 
         xmlns="urn:nucleus/schemas/package/1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Xml Documentation</name>
  <version>1.0.1</version>
  <publisher name="Inventua" url="http://www.inventua.com" email="support@inventua.com" />
  <description>
		Xml documentation viewer.
	</description>
  <compatibility minVersion="1.0.1.0" maxVersion="*" />
  <components>
    <component folderName="XmlDocumentation" optional="false">
      <moduleDefinition id="0595de3d-1ba7-49df-99f0-2e80fb00d156">
        <friendlyName>XmlDocumentation</friendlyName>
        <extension>XmlDocumentation</extension>
        <viewController>XmlDocumentation</viewController>
        <viewAction>Index</viewAction>
        <editAction>Settings</editAction>
        <categories>Content</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <file name="viewer.css" />
      <file name="viewer.min.css" />
      <folder name="Bin">
        <file name="Nucleus.XmlDocumentation.dll" />
      </folder>
      <folder name="Views">
        <file name="Viewer.cshtml" />
        <file name="_RenderClass.cshtml" />
        <file name="_RenderMember.cshtml" />
        <file name="_RenderMixedContent.cshtml" />
        <file name="_RenderMixedContentTemplate.cshtml" />
        <file name="Settings.cshtml" />
      </folder>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.TikaServerConverter/Package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="6ef525da-4858-4d7d-805b-f8c05d478ed4" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>TikaServerConverter</name>
  <version>1.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus" email="support@inventua.com" />
  <description>
		File converter extension used to convert documents using an Apache Tika Server.
	</description>
  <compatibility minVersion="2.1.0.0" maxVersion="*" />
  <components>
    <component folderName="TikaServerConverter" optional="false">
      <controlPanelExtensionDefinition id="8e8c2c25-9dda-4e05-8120-e7b4f4f608ac">
        <friendlyName>Tika Server Converter</friendlyName>
        <helpUrl>https://www.nucleus-cms.com/other-extensions/tika-server-converter/</helpUrl>
        <description>Configure Apache Tika Server converter settings.</description>
        <controllerName>TikaServerConverterSettingsController</controllerName>
        <extensionName>TikaServerConverter</extensionName>
        <scope>Site</scope>
        <editAction>Settings</editAction>
        <icon>&lt;svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -830 960 960" fill="#5f6368"&gt;&lt;path d="M400-280h160v-80H400v80Zm0-160h280v-80H400v80ZM280-600h400v-80H280v80Zm200 120ZM80-80v-80h102q-48-23-77.5-68T75-330q0-79 55.5-134.5T265-520v80q-45 0-77.5 32T155-330q0 39 24 69t61 38v-97h80v240H80Zm320-40v-80h360v-560H200v160h-80v-160q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H400Z"/&gt;&lt;/svg&gt;</icon>
      </controlPanelExtensionDefinition>
      <file name="readme.txt" />
      <!-- 
        when the project property GenerateEmbeddedFilesManifest=true and your static resources Build Action=Embedded resource, static resource
        files do not need to be included in package.xml (this file) 
      -->
      <!--<file name="viewer.css" />
			<file name="settings.css" />-->
      <folder name="bin">
        <file name="Nucleus.Extensions.TikaServerConverter.dll" />
      </folder>
      <!-- 
        when the project property RazorCompileOnBuild=true view (.cshtml) files do not need to be included in package.xml (this file) 
      -->
      <!--<folder name="Views">
				<file name="_ViewImports.cshtml" />
				<file name="Viewer.cshtml" />
				<file name="Settings.cshtml" />
			</folder>-->
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.TextHtml/package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="4036fdb6-6114-4740-b3c4-d3dbc8f37540" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Text/Html</name>
  <version>2.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus/" email="support@inventua.com" />
  <description>
    The Text/HTML module renders HTML or text content.  You can set formatting, bold/italic, insert links to other web sites, page 
    links and image links, and add lists. 
  </description>
  <compatibility minVersion="2.0.0.0" maxVersion="2.*" />
  <components>
    <component folderName="TextHtml" optional="false">
      <moduleDefinition id="b516d8dd-c793-4776-be33-902eb704bef6">
        <friendlyName>Html</friendlyName>
        <helpUrl>https://www.nucleus-cms.com/documentation/modules/texthtml/</helpUrl>
        <extension>TextHtml</extension>
        <viewController>TextHtml</viewController>
        <viewAction>Index</viewAction>
        <editAction>Edit</editAction>
        <categories>Content</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="bin">
        <file name="Nucleus.Modules.TextHtml.dll" />
      </folder>
      <cleanup>        
        <folder name="Views">
          <file name="Viewer.cshtml" />
          <file name="Settings.cshtml" />
        </folder>
      </cleanup>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.PageLinks/Package.xml
<package id="fdcdf6c6-9cc2-48db-990d-c33d2cc6d640" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>PageLinks</name>
  <version>2.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com" email="support@inventua.com" />
  <description>
    Displays a list of link targets for the current page.
  </description>
  <compatibility minVersion="2.0.0.0" maxVersion="2.*" />
  <components>
    <component folderName="PageLinks" optional="false">
      <moduleDefinition id="ed660e12-28c4-4baa-9dbe-d530f848a277">
        <friendlyName>Page Links</friendlyName>
        <!--<helpUrl>https://www.nucleus-cms.com/documentation/modules/page-links/</helpUrl>-->
        <extension>PageLinks</extension>
        <viewController>PageLinksViewerController</viewController>
        <settingsController>PageLinksSettingsController</settingsController>
        <viewAction>Index</viewAction>
        <editAction>Settings</editAction>
        <categories>Navigation</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <folder name="bin">
        <file name="Nucleus.Modules.PageLinks.dll" />
      </folder>
      <cleanup>
        <file name="viewer.css" />
        <file name="settings.css" />
        <file name="viewer.js" />
        <file name="viewer.min.js" />
        <file name="viewer.min.css" />
        <folder name="Views">
          <file name="_PageLinksList.cshtml" />
          <file name="Viewer.cshtml" />
          <file name="Settings.cshtml" />
        </folder>
      </cleanup>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.IFrame/Package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="6b3532f0-bb69-4d18-bc5a-4d4c8e326af5" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>IFrame</name>
  <version>2.0.0</version>
  <publisher name="Inventua" url="http://www.inventua.com" email="support@inventua.com" />
  <description>
		Module used for embedding another HTML page in your site.
	</description>
  <compatibility minVersion="2.0.0.0" maxVersion="2.*" />
  <components>
    <component folderName="IFrame" optional="false">
      <moduleDefinition id="505e91b2-df6b-49b9-b66e-770ed68db047">
        <friendlyName>IFrame</friendlyName>
        <helpUrl>https://www.nucleus-cms.com/documentation/modules/iframe/</helpUrl>
        <extension>IFrame</extension>
        <viewController>IFrameViewerController</viewController>
        <settingsController>IFrameSettingsController</settingsController>
        <viewAction>Index</viewAction>
        <editAction>Settings</editAction>
        <categories>Content</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <file name="viewer.css" />
      <file name="settings.css" />
      <folder name="Bin">
        <file name="Nucleus.Modules.IFrame.dll" />
      </folder>
      <folder name="Views">
        <file name="_ViewImports.cshtml" />
        <file name="Viewer.cshtml" />
        <file name="Settings.cshtml" />
      </folder>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Modules.FilesList/Package.xml
<package id="36bc8fd3-8e51-485f-8f38-4b9bcd41a80f" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>FilesList</name>
  <version>2.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus/" email="support@inventua.com" />
  <description>
    The Files List module presents a list of downloadable files from the specified folder.
  </description>
  <compatibility minVersion="2.0.0.0" maxVersion="2.*" />
  <components>
    <component folderName="FilesList" optional="false">
      <moduleDefinition id="aebc3074-528f-4e71-84b9-1fbb5de2b8e2">
        <friendlyName>Files List</friendlyName>
        <helpUrl>https://www.nucleus-cms.com/documentation/modules/files-list/</helpUrl>
        <extension>FilesList</extension>
        <viewController>FilesListViewerController</viewController>
        <settingsController>FilesListSettingsController</settingsController>
        <viewAction>Index</viewAction>
        <editAction>Settings</editAction>
        <categories>Content</categories>
      </moduleDefinition>
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="bin">
        <file name="Nucleus.Modules.FilesList.dll" />
      </folder>
      <cleanup>
        <file name="viewer.css" />
        <file name="settings.css" />
        <folder name="Views">
          <file name="_ViewImports.cshtml" />
          <file name="Viewer.cshtml" />
          <file name="Settings.cshtml" />
          <folder name="ViewerLayouts">
            <file name="Table.cshtml" />
            <file name="Ordered List.cshtml" />
            <file name="Unordered List.cshtml" />
            <file name="Tile.cshtml" />
          </folder>
        </folder>
      </cleanup>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.DeveloperTools/Nucleus.DeveloperTools.VisualStudioTemplates/Template Source Code/Layout Extension Project Template/Package.xml
<?xml version="1.0" encoding="utf-8"?>
<package id="$guid1$" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>$nucleus.extension.name$</name>
  <version>1.0.0</version>
  <publisher name="$publisher.name$" url="$publisher.url$" email="$publisher.email$" />
  <description>
    $nucleus.extension.description$
  </description>
  <compatibility minVersion="1.0.0.0" maxVersion="*" />
  <components>
    <component folderName="$nucleus.extension.name$" optional="false">      
      <layoutDefinition id="$guid3$">
        <friendlyName>Layout</friendlyName>
        <relativePath>Layouts\layout.cshtml</relativePath>
      </layoutDefinition>
      <containerDefinition id="$guid4$">
        <friendlyName>Container</friendlyName>
        <relativePath>Containers\container.cshtml</relativePath>
      </containerDefinition>
      
      <file name="license.txt" />
      
      <folder name="Layouts">
        <file name="layout.cshtml" />
        <file name="layout.css" />
      </folder>
      <folder name="Containers">
        <file name="container.cshtml" />
      </folder>
    </component>
  </components>
</package>

=== Inventua/nucleus-core/Nucleus.Core.Modules/Nucleus.Extensions.AzureBlobStorageFileSystemProvider/Package.xml
<package id="e27c5782-df19-462f-806c-9b6897dd8ae9" xmlns="urn:nucleus/schemas/package/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nucleus/schemas/package/1.0 http://www.nucleus-cms.com/schemas/package.xsd">
  <name>Azure Storage File System Provider</name>
  <version>3.0.0</version>
  <publisher name="Inventua" url="https://www.inventua.com/nucleus/" email="support@inventua.com" />
  <description>
		Nucleus file system provider for Azure storage.
	</description>
  <compatibility minVersion="3.0.0.0" maxVersion="3.*" />
  <components>
    <component folderName="AzureBlobStorageFileSystemProvider" optional="false">
      <file name="readme.txt" />
      <file name="license.txt" />
      <folder name="bin">
        <file name="Nucleus.Extensions.AzureBlobStorageFileSystemProvider.dll" />
        <file name="System.IO.Hashing.dll" />
        <file name="Azure.Storage.Blobs.dll" />
        <file name="Azure.Storage.Common.dll" />
        <file name="Azure.Core.dll" />
        <file name="System.ClientModel.dll" />
        <file name="System.Memory.Data.dll" />          
      </folder>
      <cleanup>
        <folder name="bin">
          <!-- these were shipped in an earlier version, but are not required because they are shipped with Nucleus 1.4.0 -->
          <file name="Microsoft.Bcl.AsyncInterfaces.dll" />
        </folder>
      </cleanup>
    </component>
  </components>
</package>
